/*
module.exports = {
  glossarySidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Automatically generate sidebar from the glossary folder
    },
  ],
};
*/



 const sidebars = {
  glossarySidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
